# This is a basic workflow to help you get started with Actions

name: Build artifacts

permissions: read-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    strategy:
      matrix:
        configuration: [py38, py39, py310, py311, py312, appimage]
        include:
          - configuration: py38
            python_version: 3.8
            build_python: ON
            build_appimage: OFF
          - configuration: py39
            python_version: 3.9
            build_python: ON
            build_appimage: OFF
          - configuration: py310
            python_version: 3.10
            build_python: ON
            build_appimage: OFF
          - configuration: py311
            python_version: 3.11
            build_python: ON
            build_appimage: OFF
          - configuration: py312
            python_version: 3.12
            build_python: ON
            build_appimage: OFF
          - configuration: appimage
            python_version: 3.11
            build_python: OFF
            build_appimage: ON

    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      BUILD_PYTHON_MODULE: ${{ matrix.build_python }}
      BUILD_APPIMAGE: ${{ matrix.build_appimage }}
      MAKE_FLAGS: -j2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download model files
        run: |
          wget -nv https://github.com/isl-org/adaptive-surface-reconstruction/releases/download/models/models.zip
          unzip models.zip
          rm models.zip

      - name: Build inside container
        uses: ./.github/actions/docker-action
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ matrix.configuration }}
          path: |
            build/a*.whl
            build/asr*.AppImage

